
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	private global::Gtk.HBox hbox2;
	private global::Gtk.Label numero1;
	private global::Gtk.Entry entrynumero1;
	private global::Gtk.HBox hbox3;
	private global::Gtk.Label numero2;
	private global::Gtk.Entry entrynumero2;
	private global::Gtk.HBox hbox4;
	private global::Gtk.Button suma;
	private global::Gtk.Label labelresultado;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.numero1 = new global::Gtk.Label ();
		this.numero1.Name = "numero1";
		this.numero1.LabelProp = global::Mono.Unix.Catalog.GetString ("numero1");
		this.hbox2.Add (this.numero1);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.numero1]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.entrynumero1 = new global::Gtk.Entry ();
		this.entrynumero1.CanFocus = true;
		this.entrynumero1.Name = "entrynumero1";
		this.entrynumero1.IsEditable = true;
		this.entrynumero1.InvisibleChar = '•';
		this.hbox2.Add (this.entrynumero1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.entrynumero1]));
		w2.Position = 1;
		this.vbox1.Add (this.hbox2);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.numero2 = new global::Gtk.Label ();
		this.numero2.Name = "numero2";
		this.numero2.LabelProp = global::Mono.Unix.Catalog.GetString ("numero2");
		this.hbox3.Add (this.numero2);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.numero2]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.entrynumero2 = new global::Gtk.Entry ();
		this.entrynumero2.CanFocus = true;
		this.entrynumero2.Name = "entrynumero2";
		this.entrynumero2.IsEditable = true;
		this.entrynumero2.InvisibleChar = '•';
		this.hbox3.Add (this.entrynumero2);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.entrynumero2]));
		w5.Position = 1;
		this.vbox1.Add (this.hbox3);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		this.hbox4.BorderWidth = ((uint)(3));
		// Container child hbox4.Gtk.Box+BoxChild
		this.suma = new global::Gtk.Button ();
		this.suma.CanFocus = true;
		this.suma.Name = "suma";
		this.suma.UseUnderline = true;
		// Container child suma.Gtk.Container+ContainerChild
		global::Gtk.Alignment w7 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w8 = new global::Gtk.HBox ();
		w8.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w9 = new global::Gtk.Image ();
		w9.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
		w8.Add (w9);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w11 = new global::Gtk.Label ();
		w11.LabelProp = global::Mono.Unix.Catalog.GetString ("Suma");
		w11.UseUnderline = true;
		w8.Add (w11);
		w7.Add (w8);
		this.suma.Add (w7);
		this.hbox4.Add (this.suma);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.suma]));
		w15.Position = 0;
		w15.Expand = false;
		w15.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.labelresultado = new global::Gtk.Label ();
		this.labelresultado.Name = "labelresultado";
		this.labelresultado.LabelProp = global::Mono.Unix.Catalog.GetString ("Resultado");
		this.hbox4.Add (this.labelresultado);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.labelresultado]));
		w16.Position = 1;
		this.vbox1.Add (this.hbox4);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox4]));
		w17.Position = 2;
		w17.Expand = false;
		w17.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 101;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.suma.Clicked += new global::System.EventHandler (this.OnSumaClicked);
	}
}
